[theme]
primaryColor = "#4DA8FF"
backgroundColor = "#0D0D0D"
secondaryBackgroundColor = "#1C1C1C"
textColor = "#F0F0F0"
font = "sans serif"

[server]
headless = true
port = 8502
address = "0.0.0.0"
maxUploadSize = 10

[browser]
gatherUsageStats = false
